(package "dired-hist"
         "0.11"
         "Traverse Dired buffer history: back, forward")

(website-url "https://github.com/Anoncheg1/dired-hist")
(keywords "convenience" "dired" "history")

(package-file "dired-hist.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
